// FIFA World Cup 2026 — 48 participating nations
// Sorted A–Z. Real qualified nations preferred; placeholder labels used only
// for intercontinental playoff spots that remained unresolved as of mid-2026.

const NATIONS = [
  'Algeria',
  'Argentina',
  'Australia',
  'Belgium',
  'Bolivia',
  'Brazil',
  'Cameroon',
  'Canada',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Croatia',
  'DR Congo',
  'Ecuador',
  'Egypt',
  'England',
  'France',
  'Germany',
  'Ghana',
  'Honduras',
  'Indonesia',
  'Iran',
  'Italy',
  'Ivory Coast',
  'Japan',
  'Kenya',
  'Mexico',
  'Morocco',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Playoff Winner A',
  'Playoff Winner B',
  'Poland',
  'Portugal',
  'Qatar',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'South Korea',
  'Spain',
  'Turkey',
  'United States',
  'Uruguay',
];

module.exports = { NATIONS };
